# Nome do workflow, que aparecerá na aba "Actions" do seu repositório no GitHub
name: Executar Testes Robot Framework

# Gatilhos: Define QUANDO esta ação deve rodar
on:
  # Roda toda vez que houver um push (commit enviado) na branch 'main'
  push:
    branches: [ main ]
  # Roda também quando um Pull Request for aberto ou atualizado para a branch 'main'
  pull_request:
    branches: [ main ]

# Trabalhos (Jobs): Define O QUE deve ser feito
jobs:
  # Nome do nosso job. Pode ser qualquer nome.
  test:
    # Define que o trabalho vai rodar na versão mais recente do Ubuntu Linux
    runs-on: ubuntu-latest

    # Passos (Steps): A sequência de ações a serem executadas
    steps:
      # Passo 1: Baixa o código do seu repositório para a máquina virtual
      - name: 1. Baixar o código do repositório
        uses: actions/checkout@v4

      # Passo 2: Configura o ambiente Python na versão que queremos
      - name: 2. Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Passo 3: Instala as dependências do projeto
      - name: 3. Instalar as dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Executar a suíte de testes completa do Robot Framework
      - name: 4. Executar os testes Robot
        run: python -m robot --variable BROWSER:headlesschrome -d results tests/

      # Passo 5 (Opcional, mas muito recomendado): Salvar os relatórios como artefatos
      # Este passo sempre roda (if: always()), mesmo se os testes falharem, para podermos ver os logs.
      - name: 5. Fazer upload dos relatórios
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # Nome do "pacote" de artefatos que será gerado
          name: robot-framework-reports
          # Caminho da pasta que queremos salvar
          path: results/